<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php

$_product->getTypeId();

if($_product->getTypeId() == 'configurable'){
   
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();

    $stockItem = $objectManager->get('\Magento\CatalogInventory\Model\Stock\StockItemRepository');
    $_configChild = $_product->getTypeInstance()->getUsedProductIds($_product);
 //print_r($_configChild);
    $qty=0;

    foreach ($_configChild as $child){
        
        $productStock = $stockItem->get($child);
        
        $qty=$qty+$productStock->getQty();
    }

}

?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
    <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
        <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
    </div>
    <?php if($_product->getTypeId() == 'configurable'){ ?>
    <div class="availability only">
        <?php echo __('Only')?> <strong><?php echo $qty?></strong><?php echo __(' left')?>
    </div>
    <?php } ?>
<?php else: ?>
    <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
        <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
    </div>
    
<?php endif; ?>
<?php endif; ?>
