<?php /** * Copyright © 2013-2017 Magento, Inc. All rights reserved. * See COPYING.txt for license details. */ ?> <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface'); $baseUrl=$storeManager->getStore()->getBaseUrl(); ?> <div class="footer-sec"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-lowest-payment-icons')->toHtml();?> <small class="copyright"><span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span></small> <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-lowest-page-links')->toHtml();?></div><!-- script written start in app/design/frontend/TemplateMonster/theme007/Magento_Theme/templates/html/copyright.phtml --><script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){ 
	$(document).ready(function() {
		$(".page-wrapper .slider-pro-wrapper").each(function(i) {
			$(this).addClass("item" + (i+1));
		});
	});
});</script><script type="text/javascript">
require(['jquery'], function(){
	jQuery(document).ready(function(){
		jQuery('.hide-header-info').click(function(){

			jQuery('.header-info').fadeOut();
		});
		jQuery('body').on('click', '.plusqty', function() {
			var cartItemId = jQuery(this).attr('id').split('-')[1];
			var carrentval =jQuery('#cart-item-'+cartItemId+'-qty').val();

			carrentval = parseInt(carrentval)+1;

			jQuery('#cart-item-'+cartItemId+'-qty').val(carrentval);
			jQuery('#update-cart-item-'+cartItemId).show();
		});


		
		jQuery('body').on('click', '.minusqty', function() {

			var cartItemId = jQuery(this).attr('id').split('-')[1];
			var carrentval =jQuery('#cart-item-'+cartItemId+'-qty').val();
			if(carrentval >= 1 ){
				carrentval = parseInt(carrentval)-1;
				jQuery('#cart-item-'+cartItemId+'-qty').val(carrentval);

				jQuery('#update-cart-item-'+cartItemId).show();

			}

		});

		jQuery('body').on('click', '.close-me', function() {

			jQuery('.showcart').click();
			});
	});
	
});</script><!-- script end in app/design/frontend/TemplateMonster/theme007/Magento_Theme/templates/html/copyright.phtml -->